<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StocksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
                ["symbol" => "ACTIVISION BLIZZARD INC"], 
                ["symbol" => "ADOBE INC."], 
                ["symbol" => "ADVANCED MICRO DEVICES INC."], 
                ["symbol" => "AGORA INC. ADS"], 
                ["symbol" => "AIRBNB INC."], 
                ["symbol" => "ALPHABET INC. CLASS A"], 
                ["symbol" => "AMAZON.COM INC."], 
                ["symbol" => "ANALOG DEVICES INC."], 
                ["symbol" => "ANSYS INC."], 
                ["symbol" => "APPLE INC."], 
                ["symbol" => "APPLIED MATERIALS INC."], 
                ["symbol" => "ASML HOLDING N.V. NEW YORK REGISTRY SHA"], 
                ["symbol" => "ATLASSIAN CORP."], 
                ["symbol" => "AUTODESK INC."], 
                ["symbol" => "AUTOMATIC DATA PROCESSING INC."], 
                ["symbol" => "BAIDU INC. ADS"], 
                ["symbol" => "BILIBILI INC. ADS"], 
                ["symbol" => "BOOKING HOLDINGS INC."], 
                ["symbol" => "BROADCOM INC."], 
                ["symbol" => "CADENCE DESIGN SYSTEMS INC."], 
                ["symbol" => "CAESARS ENTERTAINMENT INC."], 
                ["symbol" => "CDW CORP."], 
                ["symbol" => "CERNER CORP."], 
                ["symbol" => "CHARTER COMMUNICATIONS INC."], 
                ["symbol" => "CINCINNATI FINANCIAL"], 
                ["symbol" => "CINTAS CORP."], 
                ["symbol" => "CISCO SYSTEMS INC."], 
                ["symbol" => "CME GROUP INC."], 
                ["symbol" => "COGNIZANT TECHNOLOGY SOLUTIONS"], 
                ["symbol" => "COMCAST CORP."], 
                ["symbol" => "COPART INC."], 
                ["symbol" => "COSTAR GROUP INC."], 
                ["symbol" => "COSTCO WHOLESALE"], 
                ["symbol" => "COUPA SOFTWARE INC."], 
                ["symbol" => "CROWDSTRIKE HOLDINGS INC."], 
                ["symbol" => "CSX CORP."], 
                ["symbol" => "DATADOG INC."], 
                ["symbol" => "DISCOVERY INC. SERIES A"], 
                ["symbol" => "DISCOVERY INC. SERIES B"], 
                ["symbol" => "DISH NETWORK CORP."], 
                ["symbol" => "DOCUSIGN INC."], 
                ["symbol" => "DOLLAR TREE INC."], 
                ["symbol" => "DRAFTKINGS INC."], 
                ["symbol" => "EBAY INC."], 
                ["symbol" => "ELECTRONIC ARTS INC."], 
                ["symbol" => "ENPHASE ENERGY INC."], 
                ["symbol" => "EQUINIX INC."], 
                ["symbol" => "ERICSSON ADS"], 
                ["symbol" => "ETSY INC."], 
                ["symbol" => "EXPEDIA GROUP INC."], 
                ["symbol" => "FACEBOOK INC."], 
                ["symbol" => "FASTENAL COMPANY"], 
                ["symbol" => "FIFTH THIRD BANCORP"], 
                ["symbol" => "FISERV INC."], 
                ["symbol" => "FORTINET INC."], 
                ["symbol" => "FOX CORP."], 
                ["symbol" => "FUTU HOLDINGS LTD."], 
                ["symbol" => "GARMIN LTD."], 
                ["symbol" => "HUAZHU GROUP LTD."], 
                ["symbol" => "HUNTINGTON BANCSHARES INC."], 
                ["symbol" => "IAC/INTERACTIVECORP"], 
                ["symbol" => "ILLUMINA INC."], 
                ["symbol" => "INTEL CORP."], 
                ["symbol" => "INTERACTIVE BROKERS GROUP INC."], 
                ["symbol" => "INTUIT INC."], 
                ["symbol" => "IQIYI INC. ADS"], 
                ["symbol" => "JD.COM INC. ADS"], 
                ["symbol" => "KEURIG DR PEPPER INC."], 
                ["symbol" => "KLA CORP."], 
                ["symbol" => "LAM RESEARCH CORP."], 
                ["symbol" => "LI AUTO INC. ADS"], 
                ["symbol" => "LIBERTY BROADBAND"], 
                ["symbol" => "LIBERTY BROADBAND"], 
                ["symbol" => "LULULEMON ATHLETICA INC."], 
                ["symbol" => "LYFT INC."], 
                ["symbol" => "MARKETAXESS HOLDINGS INC."], 
                ["symbol" => "MARRIOTT INTERNATIONAL"], 
                ["symbol" => "MARVELL TECHNOLOGY GROUP"], 
                ["symbol" => "MATCH GROUP INC."], 
                ["symbol" => "MAXIM INTEGRATED PRODUCTS INC."], 
                ["symbol" => "MERCADOLIBRE INC."], 
                ["symbol" => "MICROCHIP TECHNOLOGY INC."], 
                ["symbol" => "MICRON TECHNOLOGY INC."], 
                ["symbol" => "MICROSOFT CORP."], 
                ["symbol" => "MONDELEZ INTERNATIONAL INC."], 
                ["symbol" => "MONGODB INC."], 
                ["symbol" => "MONSTER BEVERAGE"], 
                ["symbol" => "NASDAQ INC."], 
                ["symbol" => "NETEASE INC. ADS"], 
                ["symbol" => "NETFLIX INC."], 
                ["symbol" => "NORTHERN TRUST CORP."], 
                ["symbol" => "NVIDIA CORP."], 
                ["symbol" => "NXP SEMICONDUCTORS N.V."], 
                ["symbol" => "O REILLY AUTOMOTIVE INC."], 
                ["symbol" => "OKTA INC."], 
                ["symbol" => "OLD DOMINION FREIGHT LINE INC."], 
                ["symbol" => "PACCAR INC."], 
                ["symbol" => "PAYCHEX INC."], 
                ["symbol" => "PAYPAL HOLDINGS INC."], 
                ["symbol" => "PENN NATIONAL GAMING INC."], 
                ["symbol" => "PEPSICO INC."], 
                ["symbol" => "PINDUODUO INC. ADS"], 
                ["symbol" => "QORVO INC."], 
                ["symbol" => "QUALCOMM INC."], 
                ["symbol" => "QUALTRICS INTERNATIONAL INC."], 
                ["symbol" => "ROKU INC."], 
                ["symbol" => "ROSS STORES INC."], 
                ["symbol" => "RYANAIR HOLDINGS PLC ADS"], 
                ["symbol" => "SBA COMMUNICATIONS"], 
                ["symbol" => "SEAGATE TECHNOLOGY PLC"], 
                ["symbol" => "SIRIUS XM HOLDINGS INC."], 
                ["symbol" => "SKYWORKS SOLUTIONS INC."], 
                ["symbol" => "SPLUNK INC."], 
                ["symbol" => "SS&C TECHNOLOGIES HLD."], 
                ["symbol" => "STARBUCKS CORP."], 
                ["symbol" => "STONECO LTD."], 
                ["symbol" => "SVB FINANCIAL GROUP"], 
                ["symbol" => "SYNOPSYS INC."], 
                ["symbol" => "T. ROWE PRICE GROUP INC."], 
                ["symbol" => "TAKE-TWO INTERACTIVE SOFTWARE"], 
                ["symbol" => "TERADYNE INC."], 
                ["symbol" => "TESLA INC."], 
                ["symbol" => "TEXAS INSTRUMENTS INC."], 
                ["symbol" => "THE KRAFT HEINZ CO."], 
                ["symbol" => "THE TRADE DESK INC."], 
                ["symbol" => "TRACTOR SUPPLY CO."], 
                ["symbol" => "TRIMBLE INC."], 
                ["symbol" => "ULTA BEAUTY INC."], 
                ["symbol" => "UNITED AIRLINES HLD."], 
                ["symbol" => "VERISIGN INC."], 
                ["symbol" => "VERISK ANALYTICS INC."], 
                ["symbol" => "VIACOMCBS INC."], 
                ["symbol" => "VIACOMCBS INC."], 
                ["symbol" => "WARNER MUSIC GROUP"], 
                ["symbol" => "WESTERN DIGITAL"], 
                ["symbol" => "WILLIS TOWERS WATSON PUBLIC"], 
                ["symbol" => "WORKDAY INC."], 
                ["symbol" => "XILINX INC."], 
                ["symbol" => "XP INC."], 
                ["symbol" => "YANDEX N.V."], 
                ["symbol" => "ZEBRA TECHNOLOGIES"], 
                ["symbol" => "ZILLOW GROUP INC."], 
                ["symbol" => "ZILLOW GROUP INC."], 
                ["symbol" => "ZOOM VIDEO COMMUNICATIONS INC."], 
                ["symbol" => "ZOOMINFO TECHNOLOGIES INC."], 
                ["symbol" => "ZSCALER INC."],
        ];

        \App\Models\Symbol::insert($arr);
    }
}
