<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SymbolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
           
                ["symbol" => "AUD/CAD"],
                ["symbol" => "AUD/CHF"],
                ["symbol" => "AUD/CZK"],
                ["symbol" => "AUD/DKK"],
                ["symbol" => "AUD/HKD"],
                ["symbol" => "AUD/HUF"],
                ["symbol" => "AUD/JPY"],
                ["symbol" => "AUD/MXN"],
                ["symbol" => "AUD/NOK"],
                ["symbol" => "AUD/NZD"], 
                ["symbol" => "AUD/PLN"], 
                ["symbol" => "AUD/SEK"], 
                ["symbol" => "AUD/SGD"], 
                ["symbol" => "AUD/USD"], 
                ["symbol" => "AUD/ZAR"], 
                ["symbol" => "CAD/CHF"], 
                ["symbol" => "CAD/CZK"], 
                ["symbol" => "CAD/DKK"], 
                ["symbol" => "CAD/HKD"], 
                ["symbol" => "CAD/HUF"], 
                ["symbol" => "CAD/JPY"], 
                ["symbol" => "CAD/MXN"], 
                ["symbol" => "CAD/NOK"], 
                ["symbol" => "CAD/PLN"], 
                ["symbol" => "CAD/SEK"], 
                ["symbol" => "CAD/SGD"], 
                ["symbol" => "CAD/ZAR"], 
                ["symbol" => "CHF/CZK"], 
                ["symbol" => "CHF/DKK"], 
                ["symbol" => "CHF/HKD"], 
                ["symbol" => "CHF/HUF"], 
                ["symbol" => "CHF/JPY"], 
                ["symbol" => "CHF/MXN"], 
                ["symbol" => "CHF/NOK"], 
                ["symbol" => "CHF/PLN"], 
                ["symbol" => "CHF/SEK"], 
                ["symbol" => "CHF/SGD"], 
                ["symbol" => "CHF/TRY"], 
                ["symbol" => "CHF/ZAR"], 
                ["symbol" => "DKK/CZK"], 
                ["symbol" => "DKK/HKD"], 
                ["symbol" => "DKK/HUF"], 
                ["symbol" => "DKK/MXN"], 
                ["symbol" => "DKK/NOK"], 
                ["symbol" => "DKK/PLN"], 
                ["symbol" => "DKK/SEK"], 
                ["symbol" => "DKK/SGD"], 
                ["symbol" => "DKK/ZAR"], 
                ["symbol" => "EUR/AUD"], 
                ["symbol" => "EUR/CAD"], 
                ["symbol" => "EUR/CHF"], 
                ["symbol" => "EUR/CZK"], 
                ["symbol" => "EUR/DKK"], 
                ["symbol" => "EUR/GBP"], 
                ["symbol" => "EUR/HKD"], 
                ["symbol" => "EUR/HUF"], 
                ["symbol" => "EUR/JPY"], 
                ["symbol" => "EUR/MXN"], 
                ["symbol" => "EUR/NOK"], 
                ["symbol" => "EUR/NZD"], 
                ["symbol" => "EUR/PLN"], 
                ["symbol" => "EUR/SEK"], 
                ["symbol" => "EUR/SGD"], 
                ["symbol" => "EUR/TRY"], 
                ["symbol" => "EUR/USD"], 
                ["symbol" => "EUR/ZAR"], 
                ["symbol" => "GBP/AUD"], 
                ["symbol" => "GBP/CAD"], 
                ["symbol" => "GBP/CHF"], 
                ["symbol" => "GBP/CZK"], 
                ["symbol" => "GBP/DKK"], 
                ["symbol" => "GBP/HKD"], 
                ["symbol" => "GBP/HUF"], 
                ["symbol" => "GBP/JPY"], 
                ["symbol" => "GBP/MXN"], 
                ["symbol" => "GBP/NOK"], 
                ["symbol" => "GBP/NZD"], 
                ["symbol" => "GBP/PLN"], 
                ["symbol" => "GBP/SEK"], 
                ["symbol" => "GBP/SGD"], 
                ["symbol" => "GBP/USD"], 
                ["symbol" => "GBP/ZAR"], 
                ["symbol" => "JPY/CZK"], 
                ["symbol" => "JPY/DKK"], 
                ["symbol" => "JPY/HKD"], 
                ["symbol" => "JPY/HUF"], 
                ["symbol" => "JPY/MXN"], 
                ["symbol" => "JPY/NOK"], 
                ["symbol" => "JPY/PLN"], 
                ["symbol" => "JPY/SEK"], 
                ["symbol" => "JPY/SGD"], 
                ["symbol" => "JPY/ZAR"], 
                ["symbol" => "NOK/CZK"], 
                ["symbol" => "NOK/HKD"], 
                ["symbol" => "NOK/HUF"], 
                ["symbol" => "NOK/MXN"], 
                ["symbol" => "NOK/PLN"], 
                ["symbol" => "NOK/SEK"], 
                ["symbol" => "NOK/SGD"], 
                ["1symbol" => "NOK/ZAR"], 
                ["1symbol" => "NZD/CAD"], 
                ["1symbol" => "NZD/CHF"], 
                ["symbol" => "NZD/CZK"], 
                ["symbol" => "NZD/DKK"], 
                ["symbol" => "NZD/HKD"], 
                ["symbol" => "NZD/HUF"], 
                ["symbol" => "NZD/JPY"], 
                ["symbol" => "NZD/MXN"], 
                ["symbol" => "NZD/NOK"], 
                ["symbol" => "NZD/PLN"], 
                ["symbol" => "NZD/SEK"], 
                ["symbol" => "NZD/SGD"], 
                ["symbol" => "NZD/USD"], 
                ["symbol" => "NZD/ZAR"], 
                ["symbol" => "USD/CAD"], 
                ["symbol" => "USD/CHF"], 
                ["symbol" => "USD/CZK"], 
                ["symbol" => "USD/DKK"], 
                ["symbol" => "USD/HKD"], 
                ["symbol" => "USD/HUF"], 
                ["symbol" => "USD/JPY"], 
                ["symbol" => "USD/MXN"], 
                ["symbol" => "USD/NOK"], 
                ["symbol" => "USD/PLN"], 
                ["symbol" => "USD/SEK"], 
                ["symbol" => "USD/SGD"], 
                ["symbol" => "USD/TRY"], 
                ["symbol" => "USD/ZAR"],
        ];

        \App\Models\Symbol::insert($arr);
    }
}
